version: "3.7"
services:
  slack-poll:
    image: gcr.io/contenta-ai/slack-poll:latest
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      SLACK_POLL_DB: /data/db.sqlite
volumes:
  data:
