default:
    type: sqlite
    database: db.sqlite
    entities:
        - src/engine/entities/*.ts
    migrations:
        - src/engine/migrations/index.ts
    cli:
        migrationsDir: src/engine/migrations
